export const PURPLE_COLOR = "#4E49D6"
export const WHITE_COLOR = "white"
export const LIGHT_DARK = "#212B36"
export const DARK_COLOR = "#1F2A37"
export const ORANGE_COLOR = "#F3633E"
export const GRAY_COLOR = "#6C737F"
export const LIGHT_GRAY_COLOR = "#9A9FA5"
export const HARD_DARK_COLOR = "#161C24"
export const BANNER_GRAY_COLOR = "#F5F5F5"
export const DARK_BLUE_COLOR = "#0D006A"

